[package]
name = "subxt-macro"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
autotests = false

license = "GPL-3.0"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt"
homepage = "https://www.parity.io/"
description = "Generate types and helpers for interacting with Substrate runtimes."

[lib]
proc-macro = true

[dependencies]
subxt-codegen = { version = "0.1.0", path = "../codegen" }
