[package]
name = "subxt-cli"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

license = "GPL-3.0"
repository = "https://github.com/paritytech/subxt"
documentation = "https://docs.rs/subxt-cli"
homepage = "https://www.parity.io/"
description = "Command line utilities for working with subxt codegen"

[[bin]]
name = "subxt"
path = "src/main.rs"

[dependencies]
# perform subxt codegen
subxt-codegen = { version = "0.1.0", path = "../codegen" }